[package]
name = "rson"
version = "0.1.0"
edition = "2021"
authors = ["hockeyhurd nhurd96@gmail.com"]

[dependencies]
chrono = "0.4"
downcast-rs = "1.2.0"

[lib]
name = "rson"
path = "src/lib.rs"

[[bin]]
name = "rson"
path = "src/main.rs"
