name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {runs_on: macos-latest, name: "macOS cargo Debug", CARGO_BUILD_TYPE: "", REGRESSION_TEST_TYPE: "debug"}
          - {runs_on: macos-latest, name: "macOS cargo Release", CARGO_BUILD_TYPE: "--release", REGRESSION_TEST_TYPE: "release" }
          - {runs_on: ubuntu-latest, name: "Ubuntu cargo Debug", CARGO_BUILD_TYPE: "", REGRESSION_TEST_TYPE: "debug" }
          - {runs_on: ubuntu-latest, name: "Ubuntu cargo Release", CARGO_BUILD_TYPE: "--release", REGRESSION_TEST_TYPE: "release" }
          - {runs_on: windows-latest, name: "Windows cargo Debug", CARGO_BUILD_TYPE: "", REGRESSION_TEST_TYPE: "debug" }
          - {runs_on: windows-latest, name: "Windows cargo Release", CARGO_BUILD_TYPE: "--release", REGRESSION_TEST_TYPE: "release" }

    runs-on: ${{ matrix.toolchain.runs_on }}
    env:
      CARGO_TERM_COLOR: always
      CARGO_BUILD_TYPE: ${{ matrix.toolchain.CARGO_BUILD_TYPE }}
      REGRESSION_TEST_TYPE: ${{ matrix.toolchain.REGRESSION_TEST_TYPE }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose ${CARGO_BUILD_TYPE}
    - name: Run unit tests
      run: cargo test --verbose ${CARGO_BUILD_TYPE}
    - name: Run regression tests
      run: cd ${{github.workspace}} && bash regressionTest.sh tests ${REGRESSION_TEST_TYPE}
    - name: Run help menu
      run: cargo run --verbose ${CARGO_BUILD_TYPE} -- --help
