name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {runs_on: macos-latest, name: "macOS cargo Debug", BUILD_TYPE: ""}
          - {runs_on: macos-latest, name: "macOS cargo Release", BUILD_TYPE: "--release" }
          - {runs_on: ubuntu-latest, name: "Ubuntu cargo Debug", BUILD_TYPE: "" }
          - {runs_on: ubuntu-latest, name: "Ubuntu cargo Release", BUILD_TYPE: "--release" }
          - {runs_on: windows-latest, name: "Windows cargo Debug", BUILD_TYPE: "" }
          - {runs_on: windows-latest, name: "Windows cargo Release", BUILD_TYPE: "--release" }

    runs-on: ${{ matrix.toolchain.runs_on }}
    env:
      CARGO_TERM_COLOR: always
      BUILD_TYPE: ${{ matrix.toolchain.BUILD_TYPE }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose ${BUILD_TYPE}
    - name: Run tests
      run: cargo test --verbose ${BUILD_TYPE}
    - name: Run help menu
      run: cargo run --verbose ${BUILD_TYPE} -- --help
